development:
  clients:
    default:
      uri: mongodb+srv://mongo:mongo@cluster.tfuaw4g.mongodb.net/all?retryWrites=true&w=majority&authSource=admin
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false
